apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: tanzu-java-web-app-with-jar
spec:
  build:
    buildpacks: {}
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    path: ../../target/
  ports:
  - name: main
    port: 8080
